name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Display deployment info
        run: |
          echo "🚀 Deployment started!"
          echo "Environment: ${{ github.event.inputs.environment || 'production' }}"
          echo "Triggered by: ${{ github.event_name }}"

      - name: set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: install dependencies
        run: npm i

      - name: build project
        run: npm run build

      - name: zip artifact for deployment
        run: |
          zip -r deploy.zip . -x "node_modules/*" ".git/*" ".github/*"

      - name: upload to s3
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
        run: |
          aws configure set region $AWS_REGION
          aws s3 cp deploy.zip s3://cofac-netflic-bucket-cocochuchu503/deploy.zip

      - name: deploy to aws elastic beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "cofac-netflix-eb" \
            --version-label $GITHUB_SHA \
            --source-bundle S3Bucket="cofac-netflic-bucket-cocochuchu503",S3Key="deploy.zip"

          aws elasticbeanstalk update-environment \
            --application-name "cofac-netflix-eb" \
            --environment-name "Cofac-netflix-eb-env" \
            --version-label $GITHUB_SHA
